# Generated by Django 6.0.6 on 2026-06-25 03:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='画像ファイル')),
                ('is_approved', models.BooleanField(default=False, help_text='管理者が承認するまでゲーム内には表示されません。', verbose_name='承認フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ゲーム画像',
                'verbose_name_plural': 'ゲーム画像一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(help_text='しりとり用の読み方をひらがなで入力してください（例: りんご）。', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_hiragana', message='読み方はひらがな（および長音符「ー」）のみで入力してください。', regex='^[ぁ-んー]+$')], verbose_name='読み方（ひらがな）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='shiritori_game.gameimage', verbose_name='対象画像')),
            ],
            options={
                'verbose_name': '画像の読み方',
                'verbose_name_plural': '画像の読み方一覧',
                'ordering': ['created_at'],
                'unique_together': {('image', 'reading')},
            },
        ),
    ]
