# Generated by Django 6.0.6 on 2026-07-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiritori_game', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameimage',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
    ]
