# Generated by Django 6.0.6 on 2026-07-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiritori_game', '0004_gameimage_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagereading',
            name='display_name',
            field=models.CharField(blank=True, help_text='しりとりで選ばれた際に表示する名前（漢字やカタカナ、英語など）を設定します。空欄の場合は読み方（ひらがな）がそのまま表示されます（任意）。', max_length=100, null=True, verbose_name='表示名'),
        ),
    ]
