# Generated by Django 6.0.6 on 2026-07-19 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiritori_game', '0005_imagereading_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReadingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by_users', to='shiritori_game.imagereading', verbose_name='読み方')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_readings', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー正解実績',
                'verbose_name_plural': 'ユーザー正解実績一覧',
                'unique_together': {('user', 'reading')},
            },
        ),
    ]
